### ISSUE TITLE
Step 5 of Readme has permission issue

### ISSUE THREAD

**Issue by edyu** [zpatten/cc-chef-repo#1]
bin/librarian-chef update                    [~/dev/chef/cc-chef-repo]
NOGEMDEV:                              ztk
NOGEMDEV:                    cucumber-chef
 NOCBDEV:                            users, {:git=>"git@github.com:zpatten/chef-cookbook-users.git"}
 NOCBDEV:                             sudo, {:git=>"git@github.com:zpatten/chef-cookbook-sudo.git"}
/Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/librarian-0.1.0/lib/librarian/source/git/re (StandardError)in `run_command_internal': Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/librarian-0.1.0/lib/librarian/source/git/repository.rb:152:in `block (2 levels) in run!'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/librarian-0.1.0/lib/librarian/source/git/repository.rb:184:in`logging_command'

**Comment by zpatten** [comment]
My bad; I switched it to use the public repo URL; go ahead and `git pull`, I've fixed the Cheffile.

**Comment by edyu** [comment]
I"m seeing a couple of problems right now.
1. vagrant is not part of the Gemfile but it should be since the example uses vagrant and virtualbox.
2. it's not using chef 11.4.0

**Comment by edyu** [comment]
I don't know which vagrant you are using but I'm having problem right now:

# Logfile created on 2013-04-15 00:13:31 -0700 by logger.rb/31641

2013-04-15|07:13:31.824180|98943| INFO|              legendofkorea:log_helper.rb:33:log_page_break|==============================================
2013-04-15|07:13:31.824360|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| CHEF_REPO..............: "/Users/ed/dev/chef/cc-chef-repo"
2013-04-15|07:13:31.824425|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| CONFIG_RB..............: "/Users/ed/dev/chef/cc-chef-repo/.cucumber-chef/config.rb"
2013-04-15|07:13:31.824488|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| LABFILE................: "/Users/ed/dev/chef/cc-chef-repo/Labfile"
2013-04-15|07:13:31.824548|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| LOG_FILE...............: "/Users/ed/dev/chef/cc-chef-repo/.cucumber-chef/cucumber-chef.log"
2013-04-15|07:13:31.824611|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| PROGRAM................: "bin/cucumber-chef"
2013-04-15|07:13:31.824670|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| UNAME..................: "Darwin legendofkorea.local 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64"
2013-04-15|07:13:31.824723|98943| INFO|              legendofkorea:log_helper.rb:33:log_page_break|----------------------------------------------
2013-04-15|07:13:31.824792|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| CUCUMBER_CHEF_VERSION..: "3.0.8"
2013-04-15|07:13:31.824850|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| FOG_VERSION............: "1.10.1"
2013-04-15|07:13:31.824903|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| RUBY_ENGINE............: "ruby"
2013-04-15|07:13:31.824956|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| RUBY_PATCHLEVEL........: 392
2013-04-15|07:13:31.825012|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| RUBY_PLATFORM..........: "x86_64-darwin12.3.0"
2013-04-15|07:13:31.825066|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| RUBY_VERSION...........: "1.9.3"
2013-04-15|07:13:31.825121|98943| INFO|               legendofkorea:log_helper.rb:29:log_key_value| ZTK_VERSION............: "1.0.11"
2013-04-15|07:13:31.825171|98943| INFO|              legendofkorea:log_helper.rb:33:log_page_break|----------------------------------------------
2013-04-15|07:13:31.825228|98943| INFO|                          legendofkorea:utility.rb:135:boot|loading cucumber-chef v3.0.8
2013-04-15|07:13:31.825458|98943| INFO|                          legendofkorea:utility.rb:136:boot|boot(/Users/ed/dev/chef/cc-chef-repo/.cucumber-chef/config.rb)
2013-04-15|07:13:31.889920|98943| INFO|                           legendofkorea:command.rb:71:exec|command("/Users/ed/dev/chef/cc-chef-repo/bin/vagrant up test-lab-ed")
========[ COMMAND ]========[ ed@ ]========[ COMMAND ]========
/Users/ed/dev/chef/cc-chef-repo/bin/vagrant up test-lab-ed
========[ STARTED ]========[ ed@ ]========[ STARTED ]========
========[ STDERR ]========[ ed@ ]========[ STDERR ]========
/Users/ed/dev/chef/cc-chef-repo/Vagrantfile:21:in `<top (required)>': undefined method`configure' for Vagrant:Module (NoMethodError)
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/env.rb:71:in `load'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/env.rb:71:in`block in load_config!'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/env.rb:68:in `each'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/env.rb:68:in`load_config!'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/env.rb:24:in `load!'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/lib/vagrant/commands.rb:75:in`up'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/vagrant-0.2.0/bin/vagrant-up:27:in `block (2 levels) in <top (required)>'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary/command.rb:119:in`call'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary/command.rb:119:in `call_parser_run_block'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary/command.rb:78:in`run'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary/autorunner.rb:16:in `run'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary/autorunner.rb:8:in`run'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p392@cc-chef-repo/gems/git-style-binaries-0.2.1/lib/git-style-binary.rb:72:in `block in <top (required)>'
========[ STDOUT ]========[ ed@ ]========[ STDOUT ]========
NOGEMDEV:                              ztk
NOGEMDEV:                    cucumber-chef
========[ STOPPED ]========[ ed@ ]========[ STOPPED ]========
2013-04-15|07:13:32.278658|98943|FATAL|                          legendofkorea:command.rb:159:exec|EXCEPTION: ZTK::CommandError - "exec(\"/Users/ed/dev/chef/cc-chef-repo/bin/vagrant up test-lab-ed\", #<OpenStruct exit_code=0, silence=true, ui=#<ZTK::UI:0x007fbbfe1b5438 @stdout=#<IO:<STDOUT>>, @stderr=#IO:<STDERR>, @stdin=#IO:<STDIN>, @logger=#<ZTK::Logger filename=\"/Users/ed/dev/chef/cc-chef-repo/.cucumber-chef/cucumber-chef.log\">>, timeout=600, ignore_exit_status=false>) failed! [1]"

**Comment by edyu** [comment]
diff --git a/Gemfile b/Gemfile
index e8cb806..9a72e1a 100644
--- a/Gemfile
+++ b/Gemfile
@@ -30,8 +30,10 @@ source "https://rubygems.org"
 ###########
 # gem "chef", "10.24.0"
 # gem "chef", "11.4.0"
-gem "chef", "10.24.0"
+gem "chef", "~> 11.4.0"
 gem "librarian-chef"
+gem "vagrant"
+gem "virtualbox"

 # DEVELOPMENT GEMS
 ###################

**Comment by zpatten** [comment]
Vagrant is no longer a gem and the local version of chef does not matter.

**Comment by zpatten** [comment]
I just did the whole process yesterday; it does work.

**Comment by zpatten** [comment]
In fact I destroyed and setup over 5 labs including one after making the
chef file change.

**Comment by zpatten** [comment]
Yesterday alone that is

**Comment by zpatten** [comment]
Ensure you have the latest version of both virtual box and vagrant, do not use the gems.

**Comment by zpatten** [comment]
```
[~/code/cc-chef-repo] $ vagrant --version
Vagrant version 1.1.4
[~/code/cc-chef-repo] $ whereis vagrant
vagrant: /usr/bin/vagrant /opt/vagrant/bin/vagrant
```

Using VirtualBox 4.2.10

You may need to tweak the generated `Vagrantfile` and scale back the memory and cpu usage.
